### ISSUE TITLE
edit mode: immediate update no longer working for ProffieOS 5.x

### ISSUE THREAD

**Issue by artandtechvof** [profezzorn/lightsaber-web-bluetooth#13]
In ProffieOS 5.x the SetPreset() function checks if you are requesting the current preset;

    if (!strcmp(cmd, "set_preset") && arg) {
      int preset = strtol(arg, NULL, 0);
      if (preset != current_preset_.preset_num) {
	SetPreset(preset, true);
      }
      return true;
    }

In 4.8 and before, SetPreset was non conditional, and could therefore be used to update any change to color, font etc.

WebAPP now needs to select a different preset and return to this one, before changes take effect.
Would also be nice to have a function SetPreset callable from the serial commands, that lets you suppress the announce
SetPreset(preset,false);
Or a ResetPreset(bool)??

**Comment by artandtechvof** [comment]
With the latest 5.x version, having set_preset and change_preset solves this issue.
Having an serial command that allows to set_preset without announcing the font, would be nice though.
The change_preset, does not actually re-init the preset, when it is the current preset. 
'set_preset' from serial command always announces the  font, even if it is the current preset

What might be nice, is to have 'set_preset' always announcing the font, unless it is the current preset (like you had it before in 5.X)
Have the 'change_preset' always re-init the preset even if it is the current preset (updating altered style or colors, but does not announce font [ SetPreset(preset, false) ]. it does get a little annoying when you are tuning colors from one of the selectable styles...
In addition to these changes, make the serial command 'set_font' in ProffieOS also call the  SetPreset(preset, true). Then when selecting a new soundfont, it is automatically announced. This is also helpful when you re only using the serial monitor to alter presets.
In stead of having to call the change_preset or select_preset after modification of font, style, or track. it could also be build into the ProffieOS 5.x function

- set_track xx   changes track and calls SetPreset(current_preset_.preset_num, false) without announcing font
- set_style xx   changes style and or colors of style and calls SetPreset(current_preset_.preset_num, false) without announcing
- set_font xx   changes font and calls SetPreset(current_preset_.preset_num, true) and announces new font

This way, also app developers or hardcore serial command user would see the effect of a change immediately.

**Comment by profezzorn** [comment]
I think set_tracks takes effect immediately either way actually.
set_style has to go to SetPreset to re-initialize the styles
set_font has to go through SetPreset to re-initialize the font.

What if we want to build something that uploads a bunch of presets quickly though? All those automatic updates might get pretty annoying (and slow)

**Comment by artandtechvof** [comment]
> I think set_tracks takes effect immediately either way actually.
> set_style has to go to SetPreset to re-initialize the styles

In this case it would be nice if it can be done without announcing the font,

> set_font has to go through SetPreset to re-initialize the font.

In this case you do want to announcement of the font
 
> What if we want to build something that uploads a bunch of presets quickly though? All those automatic updates might get pretty annoying (and slow)

Fair point...

**Comment by artandtechvof** [comment]
With the latest workbench and OS6.x this is no longer an issue
